AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: escoladesoftware_blog_site
Parameters:
  BucketName:
    Description: S3 Bucket Name
    Type: String
  Environment:
    Description: Environment
    Type: String

Resources:

  SiteContentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join ["-", [!Ref Environment, !Ref BucketName]]
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: False
        BlockPublicPolicy: False
        IgnorePublicAcls: False
        RestrictPublicBuckets: False

  SiteCloudFront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: "cloudfront para site"
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
          TargetOriginId: "site_origin"
          ForwardedValues:
              Cookies:
                Forward: "none"
              QueryString: false
          ViewerProtocolPolicy: "redirect-to-https"
          MaxTTL: 60
          MinTTL: 10
          DefaultTTL: 30
        DefaultRootObject: "index.html"
        Enabled: true
        HttpVersion: String
        IPV6Enabled: false
        Origins:
          - DomainName: !GetAtt
              - SiteContentBucket
              - DomainName
            Id: "site_origin"
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 8080
              OriginProtocolPolicy: https-only
        PriceClass: PriceClass_All
        Restrictions:
          GeoRestriction:
            Locations:
              - BR
            RestrictionType: whitelist
        ViewerCertificate:
          CloudFrontDefaultCertificate: true

  SiteContentBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref SiteContentBucket
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetObject
              - s3:PutObject
            Effect: Allow
            Resource:
              - !Sub arn:aws:s3:::${Environment}-${BucketName}
              - !Sub arn:aws:s3:::${Environment}-${BucketName}/*
            Principal: '*'
