name: Deploy Site on S3 - Development
on:
  push:
    branches: [development]

jobs:
  Build-project:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Install angularCli
        run: npm install -g @angular/cli@latest

      - name: Restore dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: project-dist
          path: dist

  Deploy-infra:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Package Template
        run: |
          sam package --s3-bucket ${{ secrets.AWS_BUCKET_DEPLOY }} --template-file template.yaml --output-template-file deploy.yaml
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

      - name: Deploy Template
        run: |
          aws cloudformation deploy --template-file deploy.yaml --stack-name dev-escoladesoftware-site --capabilities CAPABILITY_NAMED_IAM --parameter-overrides  file://infra/dev.parameters.json
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

  Deploy-site:
    runs-on: ubuntu-latest
    needs: [Deploy-infra, Build-project]
    steps:
      - uses: actions/checkout@v2

      - name: Download project dist
        uses: actions/download-artifact@v3
        with:
          name: project-dist

      - name: Deploy site
        run: aws s3 sync dist/escoladesoftware/ s3://dev-escoladesoftware-site
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
